// src/components/elements/common/Button.tsx
import React from "react";

export function Button(props: Props) {
    return (
        <button
            type="button"
            className="btn btn-primary"
            disabled={props.disabled}
            onClick={props.onClick}>
            {props.text}
        </button>
    );
}

interface Props {
    text: string
    onClick: () => void
    disabled?: boolean
}

// components/Button/Button.vue
<script setup lang="ts">
const props = defineProps<Props>();
interface Props {
  text: string
  onClick: () => void
  disabled?: boolean
}
</script>
<template>
  <button type="button" class="btn btn-primary" :disabled="props.disabled" :onClick="props.onClick">
    {{ props.text }}
  </button>
</template>
