// src/components/GuildSelect.tsx
import { RESTAPIPartialCurrentUserGuild } from "discord-api-types/v10";
import _ from "lodash";
import React, { ChangeEvent, useState } from "react";
import { Guild } from "../models";

export function GuildSelect(props: Props) {
    const [guild, setID] = useState<Guild>({ id: "", name: "" });

    const guilds = _.sortBy(props.guilds, g => g.name.toLowerCase());
    const disabled = guilds.length == 0;
    const options = guilds.map(g => (<option key={g.id} value={g.id}> {g.name}</option>));
    options.unshift(<option key={0}>Choose guild...</option>);

    return (
        <div className="input-group mb-3">
            <label className="input-group-text font-monospace" htmlFor="inputGuild">Guild</label>
            <select className="form-select" disabled={disabled} onChange={onChange}>
                {options}
            </select>
            <button className="btn btn-primary" type="button" disabled={disabled} onClick={select}>Select</button>
        </div>
    );
    function onChange(e: ChangeEvent<HTMLSelectElement>) {
        const index = e.target.selectedIndex;
        if (!index) { return; }
        const s = e.target.options[index];
        setID({
            id: s.value,
            name: s.text
        });
    }
    function select() {
        props.onSelect(guild);
    }

}
interface Props {
    guilds: RESTAPIPartialCurrentUserGuild[],
    onSelect: (guild: Guild) => void
}

// components/GuildSelect.vue
<script setup lang="ts">
import _ from "lodash";

const { guildData, userData, getGuildEmojis, getGuildStickers } = useDiscord();
const guildID = useState<string>(() => "");
const guilds = computed(() => _.sortBy(userData.value.guilds, g => g.name.toLowerCase()));

const onClick = async () => {
  const guild = guilds.value.find(g => g.id == guildID.value);
  if (!guild) { return; }
  const id = guild.id;
  const name = guild.name;
  const emojis = _.sortBy(await getGuildEmojis(guildID.value), e => e.name?.toLowerCase());
  const stickers = _.sortBy(await getGuildStickers(guildID.value), s => s.name.toLowerCase())
    .filter(s => s.format_type != 3);// Lottie not supported

  guildData.value = { id, name, emojis, stickers };
};
watchEffect(() => {
  const guild = guildData.value;
  console.log(`Guild: ${guild.name}(${guild.id}) - ${guild.emojis.length} - ${guild.stickers.length}`);
});
</script>
<template>
  <div class="input-group">
    <label class="input-group-text font-monospace" htmlFor="inputGuild">Server</label>
    <select v-model="guildID" class="form-select" :disabled="guilds.length == 0">
      <option key="" value="">
        Choose server...
      </option>)
      <option v-for="guild in guilds" :key="guild.id" :value="guild.id">
        {{ guild.name }}
      </option>
    </select>
    <button class="btn btn-primary" type="button" :disabled="guildID == ''" :onClick="onClick">
      Select
    </button>
  </div>
</template>
